export const weakness = {
	normal: ["fighting"],
	fighting: ["flying", "psychic", "fairy"],
	flying: ["electric", "ice", "rock"],
	fire: ["water", "rock", "ground"],
	water: ["electric", "grass"],
	grass: ["fire", "flying", "bug", "poison", "ice"],
	electric: ["ground"],
	ground: ["water", "ice", "grass"],
	poison: ["ground", "psychic"],
	rock: ["water", "grass", "ground", "steel", "fighting"],
	dark: ["bug", "fighting", "fairy"],
	psychic: ["bug", "dark", "ghost"],
	ghost: ["ghost", "dark"],
	ice: ["fighting", "fire", "steel", "rock"],
	steel: ["fighting", "fire", "ground"],
	fairy: ["poison", "steel"],
	dragon: ["ice", "dragon", "fairy"],
	bug: ["fire", "rock", "flying"],
};